### ISSUE TITLE
Weird import bug

### ISSUE THREAD

**Issue by sayakpaul** [webdataset/webdataset#165]
I am on a GCP VM and here are the versions of the libraries involved:

PyTorch: 1.10.0
WebDataset: 0.2.4

When I run `import webdataset as wds` from a notebook it's giving:

```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_15723/2984473602.py", line 1, in <module>
    import webdataset as wds

  File "/opt/conda/lib/python3.7/site-packages/webdataset/__init__.py", line 21, in <module>
    from .cache import (

  File "/opt/conda/lib/python3.7/site-packages/webdataset/cache.py", line 43
    while data := stream.read(chunk_size):
                ^
SyntaxError: invalid syntax
```

The same thing happens from an interactive Python kernel too.

**Comment by StephanPan** [comment]
change the version of webdataset to 0.1.*
