### ISSUE TITLE
Collating a mixed modality tar file

### ISSUE THREAD

**Issue by aitothemoonandback** [webdataset/webdataset#316]
I have a few thousand tar files each containing a `text-npy` pair. The `npy` is of shape `(num_frames, H, W, 3) ` where `num_frames` can be anywhere from `1` to `N` with `N` being an integer, while H = W = 512. I currently process my dataset in the following way:
```
    pipeline.extend([
        wds.select(filter_no_caption_or_no_image),
        wds.decode(handler=log_and_continue),  # (num_frames, H, W, 3
        wds.rename(image="npy", text="txt"), #(num_frames, H, W, 3)
        wds.map_dict(image=lambda x: x, text=lambda text: tokenizer(text)[0]),
        wds.to_tuple("image", "text"),
        wds.batched(args.batch_size, partial=not is_train)
    ])
```
but I get the following error: 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/scratch/users/user/open_clip/src/training/main.py", line 508, in <module>
    main(sys.argv[1:])
  File "/scratch/users/user/open_clip/src/training/main.py", line 436, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "/scratch/users/user/open_clip/src/training/train.py", line 85, in train_one_epoch
    for i, batch in enumerate(dataloader):
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/filters.py", line 487, in _batched
    batch = collation_fn(batch)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/filters.py", line 461, in default_collation_fn
    b = np.array(list(b))
        ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1024,) + inhomogeneous part.
[rank1]:[2023-12-07 14:52:17,455] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[rank1]:[2023-12-07 14:52:17,455] torch._dynamo.utils: [INFO] Function, Runtimes (s)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/scratch/users/user/open_clip/src/training/main.py", line 508, in <module>
    main(sys.argv[1:])
  File "/scratch/users/user/open_clip/src/training/main.py", line 436, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "/scratch/users/user/open_clip/src/training/train.py", line 85, in train_one_epoch
    for i, batch in enumerate(dataloader):
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/filters.py", line 487, in _batched
    batch = collation_fn(batch)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/webdataset/filters.py", line 461, in default_collation_fn
    b = np.array(list(b))
        ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1024,) + inhomogeneous part.
[rank2]:[2023-12-07 14:52:19,860] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[rank2]:[2023-12-07 14:52:19,860] torch._dynamo.utils: [INFO] Function, Runtimes (s)
[2023-12-07 14:52:24,822] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 46574 closing signal SIGTERM
[2023-12-07 14:52:24,823] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 46577 closing signal SIGTERM
[2023-12-07 14:52:28,358] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 46575) of binary: /home/groups/jluc/user/miniconda3/bin/python
Traceback (most recent call last):
  File "/home/groups/jluc/user/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groups/jluc/user/miniconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```
Is this error happening because webdataset is attempting to collate the npys of different `num_frames` length? What is the suggested way of getting around this? How do I specify my own collate function? My model is able to ingest data of any length so this is my only obstacle. Any help or guidance is greatly appreciated!!

**Comment by tmbdev** [comment]
I'm not sure what the source of the error is from your traceback, but you can specify a custom collation function as an argument to batched: batched(collation_fn=...). Alternatively, you can set combine_tensors=False (and combine_scalars=False as well).
