### ISSUE TITLE
Writing a numpy array as `.npz` using TarWriter

### ISSUE THREAD

**Issue by yoonbo** [webdataset/webdataset#320]
When writing a numpy array in `npz` extension using TarWriter, it produces an error message.

**Reproducer:**
```
import numpy as np
import webdataset

array = np.array([[1, 2, 3], [4, 5, 6]])
tar_path = 'test_dataset.tar'
with webdataset.TarWriter(tar_path) as writer:
    data = {'__key__': 'sample', 'array.npz': array}
    writer.write(data)
```
Note that this code works if the filename is set to `"array.npy"`.

**Error message:**
```
Traceback (most recent call last):
  File "/Users/byoon/tmp/x.py", line 8, in <module>
    writer.write(data)
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 350, in write
    obj = self.encoder(obj)
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 245, in g
    return encode_based_on_extension(sample, handlers)
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 214, in encode_based_on_extension
    return {
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 215, in <dictcomp>
    k: encode_based_on_extension1(v, k, handlers) for k, v in list(sample.items())
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 202, in encode_based_on_extension1
    result = handler(data)
  File "/Users/byoon/Library/Python/3.10/lib/python/site-packages/webdataset/writer.py", line 114, in numpy_npz_dumps
    np.savez_compressed(stream, **data)
TypeError: numpy.savez_compressed() argument after ** must be a mapping, not numpy.ndarray
```

**Reason:**
When an output filename has `npz` extension, the tarwriter calls [`numpy_npz_dumps()`](https://github.com/webdataset/webdataset/blob/0.2.86/webdataset/writer.py#L106). The expected argument of this function is `data: np.ndarray`, but it passes the data to the `np.savez_compressed()` with `**data`:
```
np.savez_compressed(stream, **data)
```
as if the data is a dictionary, while it should have been
```
np.savez_compressed(stream, data=data)
```

**Comment by tmbdev** [comment]
If you just want to write a numpy array, use .npy. The .npz format is effectively a dictionary of arrays.

I have updated the code to require dictionaries and to return dictionaries for the writer and decoder.
