### ISSUE TITLE
Broken Pipe Error When Loading from S3 Bucket and End Data Loading before Exhausting the Stream

### ISSUE THREAD

**Issue by ChanZou** [webdataset/webdataset#411]
When Pytorch dataloader is derefenced and the underlying WebDataset object is garbage collected before the AWS S3 stream is exhausted, an error is raised by AWS CLI and further caught by webdataset:
```bash
download failed: <s3_url> [Errno 32] Broken pipe
Traceback (most recent call last):
  File <path_to_webdataset_package>/gopen.py", line 121, in __del__
    self.close()
  File "<path_to_webdataset_package>gopen.py", line 109, in close
    self.wait_for_child()
  File "<path_to_webdataset_package>/gopen.py", line 83, in wait_for_child
    raise IOError(f"{self.args}: exit {self.status} (read) {info}")
OSError: (('aws s3 cp <s3_url> -',), {'shell': True, 'bufsize': 8192}): exit 1 (read) {}
```
While this error makes sense to me because Pipe will close the stream in its destructor, I would still love to confirm that this is an expected behavior.
And if it's expected, I would love to know how to handle or resolve this gracefully, avoiding STDOUT and STDERR being a mess. Obviously, I can redirect STDERR to /dev/null for the AWS CLI command. But it's probably too generic and makes it unnecessarily obscure for future debugging. 
I would also argue that it's quite common to no exhaust the data stream, especially when we want to have explicit epoch length and set it with `.with_epoch()`.

Any suggestion would be greatly appreciated! Thank you for building this tool!

Below is a script to reproduce the behavior I was talking about:
```python
import math
from argparse import Namespace

import torch
import webdataset as wds
from torchvision import transforms


def get_dataloader(args):
    num_worker_batches = math.ceil(
        args.num_train_examples / (args.global_batch_size * args.num_workers)
    )  # per dataloader worker

    def preprocess_images(sample):
        image = sample["jpg"]

        return {
            "image": transforms.ToTensor()(image),
        }

    def collate_fn(samples):
        images = torch.stack([sample["image"] for sample in samples])
        images = images.to(memory_format=torch.contiguous_format).float()
        return {
            "images": images,
        }

    dataset = (
        wds.WebDataset(args.dataset_path, resampled=True)
        .decode("pil")
        .map(preprocess_images)
        .with_epoch(num_worker_batches)
    )

    dataloader = wds.WebLoader(
        dataset,
        batch_size=args.per_gpu_batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        collate_fn=collate_fn,
    )

    return dataloader


if __name__ == "__main__":
    args = Namespace(
        # Each tar file contains 100 instances
        dataset_path=[
            "pipe:aws s3 cp <s3_url_to_fake_imagenet_000000.tar> -",
        ],
        # From WebDataset example notebooks
        # dataset_path="https://storage.googleapis.com/webdataset/fake-imagenet/imagenet-train-{000000..001281}.tar",
        # Change num_train_examples to a smaller value to see the error.
        num_train_examples=100,
        per_gpu_batch_size=1,
        global_batch_size=1,
        num_workers=1,
    )
    dataloader = get_dataloader(args)
    count = 0
    for sample in dataloader:
        count += 1
    print(count)
```

**Comment by tmbdev** [comment]
Sorry for the late response. Yes, the recommended solution is to write a small wrapper script. You also have the option of declaring subprocess exit codes that should be ignored by the I/O system in WebDataset.
