### ISSUE TITLE
Processes not cleaned up?

### ISSUE THREAD

**Issue by thecooltechguy** [webdataset/webdataset#90]
Hi,

I'm currently using Webdataset to stream data from S3 for my multi-gpu Pytorch training job (using multiprocessing Dataloader workers for each gpu like typical Pytorch jobs, etc.).

For some reason, I'm finding that the first epoch goes by fine, but as soon as the second epoch finishes, I get the following error that causes the training job to fail:

```
runtime stack:
runtime.throw(0xb5e9bc, 0x9)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/panic.go:1116 +0x72
runtime.newosproc(0xc000180700)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/os_linux.go:161 +0x1ba
runtime.newm1(0xc000180700)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:1779 +0xdc
runtime.templateThread()
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:1830 +0x71
runtime.mstart1()
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:1112 +0xc3
runtime.mstart()
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/proc.go:1077 +0x6e

goroutine 1 [runnable]:
internal/poll.errnoErr(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/errno_unix.go:32
internal/poll.(*pollDesc).init(0xc00014ceb8, 0xc00014cea0, 0xc000027401, 0xc00014cea0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_poll_runtime.go:45 +0x8c
internal/poll.(*FD).Init(0xc00014cea0, 0xb5a3fb, 0x4, 0x1, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/internal/poll/fd_unix.go:63 +0x5f
os.newFile(0x3, 0xc000027460, 0x11, 0x1, 0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/file_unix.go:155 +0xf6
os.openFileNolog(0xc000027460, 0x11, 0x0, 0x0, 0xad0fa0, 0x0, 0xc0002d9868)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/file_unix.go:226 +0x18d
os.OpenFile(0xc000027460, 0x11, 0x0, 0x0, 0x7f83ca746108, 0x0, 0x9)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/file.go:307 +0x63
os.Open(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/file.go:287
github.com/aws/aws-sdk-go/internal/ini.OpenFile(0xc000027460, 0x11, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.35.13/internal/ini/ini.go:13 +0x83
github.com/aws/aws-sdk-go/aws/session.loadSharedConfigIniFiles(0xc0002da398, 0x2, 0x2, 0x80, 0xad0e60, 0x1, 0xc000204880, 0xc0002d9ba8)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.35.13/aws/session/shared_config.go:163 +0xd2
github.com/aws/aws-sdk-go/aws/session.loadSharedConfig(0xb5cc0b, 0x7, 0xc0002da398, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.35.13/aws/session/shared_config.go:145 +0xb8
github.com/aws/aws-sdk-go/aws/session.newSession(0x0, 0x0, 0xc000396c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.35.13/aws/session/session.go:446 +0x1d1
github.com/aws/aws-sdk-go/aws/session.NewSessionWithOptions(0x0, 0x0, 0xc000396c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.35.13/aws/session/session.go:333 +0x282
github.com/peak/s5cmd/storage.(*SessionCache).newSession(0x11d9410, 0xd8e560, 0xc00015cf40, 0xa, 0x0, 0x0, 0x0, 0x7ffeb7b374b3, 0x23, 0x0, ...)
	/home/runner/work/s5cmd/s5cmd/storage/s3.go:668 +0x4a9
github.com/peak/s5cmd/storage.newS3Storage(0xd8e560, 0xc00015cf40, 0xa, 0x0, 0x0, 0x0, 0x7ffeb7b374b3, 0x23, 0xc0002dba78, 0x5a8f06, ...)
	/home/runner/work/s5cmd/s5cmd/storage/s3.go:84 +0xda
github.com/peak/s5cmd/storage.NewRemoteClient(0xd8e560, 0xc00015cf40, 0xc000204580, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/s5cmd/s5cmd/storage/storage.go:57 +0xeb
github.com/peak/s5cmd/command.Cat.Run(0xc000204580, 0xb59d05, 0x3, 0xc00002e140, 0x9f, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/s5cmd/s5cmd/command/cat.go:74 +0x9c
github.com/peak/s5cmd/command.glob..func5(0xc00015d400, 0x0, 0x0)
	/home/runner/work/s5cmd/s5cmd/command/cat.go:59 +0x308
github.com/urfave/cli/v2.(*Command).Run(0x11d1a20, 0xc00015d340, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0x11d2a80, 0xd8e560, 0xc00015cf40, 0xc00001e0a0, 0x5, 0x5, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/peak/s5cmd/command.Main(0xd8e560, 0xc00015cf40, 0xc00001e0a0, 0x5, 0x5, 0x0, 0x0)
	/home/runner/work/s5cmd/s5cmd/command/app.go:140 +0x197
main.main()
	/home/runner/work/s5cmd/s5cmd/main.go:23 +0xaf

goroutine 6 [runnable]:
os/signal.signal_enable(0x3bb5377700000002)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sigqueue.go:219 +0x6c
os/signal.enableSignal(...)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/signal/signal_unix.go:51
os/signal.Notify.func2(0x2)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/signal/signal.go:150 +0x8e
os/signal.Notify(0xc000194000, 0xc00012c7a8, 0x2, 0x2)
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/signal/signal.go:162 +0x170
main.main.func1(0xc0003965d0)
	/home/runner/work/s5cmd/s5cmd/main.go:17 +0xa6
created by main.main
	/home/runner/work/s5cmd/s5cmd/main.go:15 +0x73

goroutine 17 [syscall]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.14.12/x64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/opt/hostedtoolcache/go/1.14.12/x64/src/os/signal/signal.go:127 +0x44

goroutine 7 [chan receive]:
github.com/peak/s5cmd/log.(*Logger).out(0xc00000dd60)
	/home/runner/work/s5cmd/s5cmd/log/log.go:88 +0x127
created by github.com/peak/s5cmd/log.New
	/home/runner/work/s5cmd/s5cmd/log/log.go:61 +0xc7

runtime: failed to create new OS thread (have 6 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime: failed to create new OS thread (have 2 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

Now, this error is actually thrown by s5cmd, which is the s3 tool I use within Webdataset to pipe data in from S3 at high throughputs. 

However, since I only get this error at the end of the second epoch (and the first epoch goes by fine), I was wondering if somehow, Webdataset was not killing each s5cmd process as soon as it finishes piping in data from its specific s3 file, causing the number of open processes to grow over time and eventually reach a max limit and error out at the end of the second epoch.

I'm running this on Docker in AWS EKS, and the host node's `ulimit -a` is:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30446
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 8192
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Furthermore, in the EKS docker host node's docker daemon config, I see this:

```
# The max number of open files for the daemon itself, and all
# running containers.  The default value of 1048576 mirrors the value
# used by the systemd service unit.
DAEMON_MAXFILES=1048576
```

So, I wanted to post an issue here to ask if there's a bug in how Webdataset cleans up processes that pipe data in from S3?

I tested my pipeline by just switching out the s3 data inputs with local file inputs, and everything works perfectly fine. So it appears that the way Webdataset is handling these data input processes may be causing the issue.

Would appreciate any help, and thanks for the awesome library! :)

**Comment by tmbdev** [comment]
WebDataset doesn't kill processes at all, it just creates a Pipe object and runs whatever command you ask it to in it. The webdataset reader is finished whenever the job finishes, so there is usually no need to kill anything. The only way processes hang around is if you start an epoch, stop before it finishes, and then start another one.

I think the Golang error message is misleading; errno=11 can be caused by many different resource shortages, not just max user processes. In your case, max user processes seems unlimited.

```
runtime: failed to create new OS thread (have 2 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

My guess is that you are running out of some resource needed for subprocess creation; it might just be memory.  But it's also possible that EKS imposes some CPU limits. Have you tried increasing memory and CPU limits in the pod spec?

**Comment by thecooltechguy** [comment]
Hi @tmbdev , thanks for the reply! The EKS nodes themselves (p4d.24xlarge) have ~1 TB+ of memory, and each pod doesn't have any cpu/memory limits since each pod is assigned to its own instance and is the only main pod running on each training node.

Also, I monitored the cpu and memory usage while the job is running up until that error above, but the cpu and memory usage don't go anywhere near the total amount of resources available.

However, since I'm using Lightning with Webdataset in a distributed training setup, I'm using Lightning's `limit_train_batches` flag to set the number of training batches that each gpu must processes in an epoch, which is not equal to the true dataset length, so I'm thinking this can cause the processes to hang around, since, as you mentioned, this would be stopping an epoch before it finishes and then starting another one. So I'm debugging if this is the case right now.

**Comment by thecooltechguy** [comment]
@tmbdev When using Webdataset to train in a distributed setup with a large dataset that is streamed from cloud storage, what would be the recommended way to set this up, so that the entire dataset is only processed only once per training job (as the dataset is huge), but at the same time, Webdataset's pipe processes reading from the cloud storage are killed with each new "epoch" (where "epochs" in this case would occur throughout the training job, as it progresses through the entire dataset one time)?

I'm only using Lightning's `limit_train_batches` in order to ensure that each gpu receives an equal amount of training samples (since if I don't do this, the training can hang due to unequal samples among the gpus), but since Webdataset doesn't kill any of the processes like you mentioned, it is definitely possible for these processes to be stacking up in the background as new "epochs" are started.

**Comment by tmbdev** [comment]
I'm not sure how `limit_train_batches` interacts with WebDataset; I need to investigate that further.

WebDataset has its own means of ensuring that the same number of batches is given to each worker. The simplest is something like this:

```
# repeatedly iterate through shards in each worker and set the epoch size to the given number.
ds = WebDataset(urls, ...). ...
dl = WebLoader(ds, ...).ddp_equalize(n)
```

Any attempt to equalize the number of shards between workers will influence training statistics slightly (that's true also for `limit_train_batches`), and there are different tradeoffs you can make.

Statistically the cleanest is probably training by resampling (sampling with replacement):

```
# repeatedly iterate through shards in each worker and set the epoch size to the given number.
shards = wds.ResampledShards(urls)
ds = WebDataset(shards, ...).with_epoch(n, by_node=True).shuffle(nshuffle). ...
```

**Comment by tmbdev** [comment]
Could you check please whether you are actually running out of processes, by running a "ps"?

The DataLoader will create one WebDataset instance per worker; when the DataLoader worker dies, that should close all its file descriptors kill all its subprocesses as well, so I don't see how why additional subprocesses would hang around.

TODO: add additional checking for cleanup in WebDataset and explicit closing/killing on gc

**Comment by thecooltechguy** [comment]
Hi @tmbdev , so in my Webdataset setup, I've been using `repeat=True` in the `Webdataset` constructor (in addition to Lightning's `limit_{train/val/test}_batches`), and just creating a regular Pytorch Dataloader from this Webdataset (instead of a WebLoader). 

Is this functionally equivalent to the 2 other suggestions you mentioned above?

Also, interestingly, I'm finding that as soon as the dataset gets repeated mid-epoch, my memory usage very quickly explodes and causes s5cmd and other processes to fail due to OOM (cannot fork process, resource busy/unavailable error, etc.). This memory explosion happens so quickly at this point in the training (when the iterator is repeated), that I missed and mistakenly believed that this wasn't due to a memory issue. But this doesn't happen if the Webdataset pipes just cat the files from local file system storage, rather only when I use aws cil/s5cmd process pipes to read data from S3.

I will try replacing my `repeat=True` flag with the 2 approaches you suggested to see if the problem goes away.

**Comment by thecooltechguy** [comment]
@tmbdev So I tried disabling the repeat and just set the number of steps to be lower than the exact number of steps needed to go through 1 epoch, and when doing this, the issue does not come up immediately at the same time that it would usually come up when using `repeat=True` (ie., sometime in the first epoch).

This time, however, the issue comes up at the end of the 4th/5th epoch, so it seems like the repeating part may not be the root cause of the issue. 

And given that my current setup works perfectly fine if I just switch the actual pipe commands passed into WebDataset with just a list of local files, it seems that somehow the launched `s5cmd` and `aws s3` processes are not being cleaned up.

**Before I continue, here's some information about my environment:**

- The exact pipe commands I'm passing into Webdataset are of the following format: `pipe:s5cmd --log debug --numworkers 1 cat {s3 uri to a shard file}`. I also tried running some sample `s5cmd` with this same format in the terminal, and I was able to verify that only 1 processes i created for each of these `s5cmd` command I run.
- I'm training on a single p4d.24xlarge instance (8 gpus). For each gpu, the number of pytorch Dataloader workers that I'm using is 12. I tried reducing the number of workers to very small values (like 2, 4, etc.), but the issue still eventually arises.
- I'm running this within a Docker container on Kubernetes with ample resource requests (~96 cpus, 900 gb memory, etc., which are basically the p4d instance's limits).

**Processes**:
Following your suggestion, I also monitored the total number of running `s5cmd` processes throughout the training job using the following command: `watch "ps -e --no-headers | grep s5cmd | wc -l"`. 

I find that, during the "training" portion of the first epoch, the total number of s5cmd processes hovers around 96, which is expected, since I'm using 8 gpus, and each gpu's DataLoader uses 12 workers (and since each dataloader worker's `s5cmd` pipe command only spawns 1 processes, this gives us an expected 8 * 12 * 1 = 96 workers).

However, as soon as the validation portion of the first epoch starts, the total number of running s5cmd processes spikes up to 700+. This is strange for me, since the validation dataloader (with the exact same WebDataset setup, except with different s3 shard files) also has 12 workers per gpu, so at most, I was expecting that the total number of running workers at this point in the first epoch (right when the validation phase starts) should be around 96 (since the training dataloader workers should have been killed and only the validation dataloader workers should be spawned and alive at this point in time). Even if we consider that the training dataloaders aren't killed yet during the validation phase of the first epoch, this should still only give us at most 96 + 96 = 192 running `s5cmd` processes, right?

And in the subsequent epochs, the total number of running processes fluctuate between ~800 and ~4000+, based on when the epochs start and stop (until eventually the issue arises and halts training), which is also confusing for me, since I don't understand how my setup (as described above) can cause such large number of processes. Furthermore, when inserting some print statements within Webdataset's `gopen.Pipe` `close` method, I find that the statuses of many of the pipes when they are opened/closed within Webdataset are `141`, `0`, or `None`. I think `0` and `None` are okay and expected, but I'm not sure where the `141` status code comes from.

**Comment by thecooltechguy** [comment]
After multiple tests, I've found that it is the caching that is most likely causing the issue. 

If I disable caching, then the number of processes stays within the expected bounds (96 total s5cmd processes during training, and 96 + 96 = 192 total s5cmd processes during validation) for every epoch, and no issues occur.

If I enable caching, though, then the number of processes begins to consistently explode within the first epoch, until the number of processes becomes very large and the issue arises.

I ran a couple of trials of this and this behavior remains consistent.

So, maybe the current shard caching code is perhaps not closing the piped stream and process correctly after writing the shard files?

I looked at the code, and I can see that `stream.close()` is called in the `CacheStream`'s `close()` function, so I'm not sure exactly where in this caching logic the error is at.

I'm debugging this now, and if I find anything I'll post it here, but just wanted to share this with you @tmbdev , in case you might have an idea of what might be causing this issue within the caching function.

Thanks again for the time and help! If I find the solution to this issue, I can submit a PR with the resolution.

**Comment by thecooltechguy** [comment]
I think I've now fixed the bug.

I think what was happening was that, even when caching is enabled, Webdataset will still first `gopen`s the input urls, and then check the cache to see if the cached file for the url exists. However, the problem with this is that, when using pipes of commands (like `s5cmd` in my case), `gopen`ing the url first will always launch the command process (using the `gopen.Pipe` class) and create the pipe to read from the process's `stdout` (even if the url's shard has been cached, in which case we shouldn't be launching the process in the first place). 

Then, the next time that same url is iterated on, Webdataset again first `gopen`s the url, and then later realizes that it exists in cache, at which point it will just discard the `gopen`ed stream and just read from cache. However, the discarded `gopen` would have already launched a new process for that url's command. And since the cache reads are much faster than reading from the cache files streamed in from S3, this leads to an increased rate of new `s5cmd` processes launched once all of the epoch's files have been cached.

To resolve this, I've tried the following work-around:

In `dataset.py`'s code section for the `Webdataset` class:

```python
    # result = result.then(tariterators.url_opener, handler=handler)
    if cache_dir:
        result = result.then(
            shardcache.cacheable_url_opener,
            handler=handler, 
            cache_dir=cache_dir, 
            cache_size=cache_size, 
            cache_name=cache_name, 
            verbose=cache_verbose
        )
        # result = result.then(
        #     shardcache.cache_shards,
        #     cache_dir=cache_dir,
        #     cache_size=cache_size,
        #     cache_name=cache_name,
        #     verbose=cache_verbose,
        # )
    else:
        result = result.then(tariterators.url_opener, handler=handler)
```

And in `shardcache.py`, I've added a new function:

```python
def cacheable_url_opener(data, handler=reraise_exception, cache_dir="./data", cache_size=1e15, cache_name=guess_shard, verbose=False, **kw):
    # Create the cache directory if it doesn't exist
    if cache_dir is not None:
        os.makedirs(cache_dir, exist_ok=True)
    
    for sample in data:
        assert isinstance(sample, dict), sample
        assert "url" in sample
        url = sample["url"]
        try:
            # Check if caching is enabled
            if cache_dir:
                # Caching is enabled
                
                # Check if this url's shard has already been cached
                cache_path = os.path.join(cache_dir, cache_name(url))
                
                if os.path.exists(cache_path):
                    # This url's shard has been cached, so just open it and yield its stream
                    if verbose:
                        print("[opening cached", cache_path, "] ", file=sys.stderr, flush=True)
                    yield dict(url=url, stream=open(cache_path, "rb"))
                else:
                    # create a gopen'ed stream of the url 
                    # and use it to return a CacheStream of this url.
                    stream = gopen.gopen(url, **kw)
                    _cache = CacheStream(cache_path, stream, verbose=verbose)
                    yield dict(url=url, stream=_cache)
                    
                if verbose:
                    print(f"[finished {cache_path}]", file=sys.stderr, flush=True)
            else:
                # Caching is disabled, so return a regular gopen'ed stream of this url
                stream = gopen.gopen(url, **kw)
                sample.update(stream=stream)
                yield sample
        
        except Exception as exn:
            exn.args = exn.args + (url,)
            if handler(exn):
                continue
            else:
                break
```

I'm still testing this to confirm that this fully fixes the issue, but does this look like an acceptable fix @tmbdev ?

**Comment by tmbdev** [comment]
Thanks for figuring this out! We hadn't seen that bug because we use caching mainly for desktop testing (all large scale training uses AIStore or object stores).

I'll add the fix to WebDataset.

**Comment by EEthinker** [comment]
@tmbdev Have you added this fix to webdataset yet?

**Comment by EEthinker** [comment]
When I use repeat = True in webdataset construction, my dataloader cannot proceed to the second batch: it just stops after loading the first batch. Would it be related to this bug?

**Comment by steve-z-seattle** [comment]
I am facing perhaps exactly the issue that @thecooltechguy faced, except that I am curling from a standard http url, not S3. I monitored the number of curl has been running, and it increases every time the training starts (which reads the data using curl). So I think the are still issues here.

I will try to run the same process, but with caching disabled, and report back. If the issues goes away, then the root cause would be the caching.

**Comment by steve-z-seattle** [comment]
Since I am not using cache, I suspect that maybe because the training discards the last batch? Any idea? thanks.

**Comment by steve-z-seattle** [comment]
This is not an issue for me anymore, as the client passed in persistent_workers=True. Turning that off solves the issue.

**Comment by bryant1410** [comment]
I'm thinking maybe #270 is related? Because these issues seem to show up when the epoch is exited early and the workers are persisted. So the streams that were already loaded aren't closed cleanly.
