### ISSUE TITLE
How to work with `npz` files?

### ISSUE THREAD

**Issue by brtasavpatel** [webdataset/webdataset#93]
I am trying to create a webdataset containing `npz` files.
There's one master `metadata.csv` which have references to the labels, images and other metadata for the images.

here's my sample code snippet.
```
def image_samples(csv_path="metadata.csv"):
	df = pd.read_csv(csv_path)
	for row in df.itertuples():
		image_save_path, label_save_path = row.image_npz_save_path, row.label_save_path
		sample = {
			"__key__" : row.image_id,
			"image": np.load(image_save_path),
			"label": np.load(label_save_path)
		}
		yield sample  
with wds.ShardWriter("dataset-%06d.tar", maxcount=50) as sink:
	for sample in islice(image_samples(), 0, 100):
		sink.write(sample)
        
# writing dataset-000000.tar 0 0.0 GB 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-a15e80b2f441>", line 15, in <module>
    sink.write(sample)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 336, in write
    size = self.tarstream.write(obj)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 250, in write
    obj = self.encoder(obj)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 154, in encoder
    return encode_based_on_extension(sample, handlers)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 129, in encode_based_on_extension
    k: encode_based_on_extension1(v, k, handlers) for k, v in list(sample.items())
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 129, in <dictcomp>
    k: encode_based_on_extension1(v, k, handlers) for k, v in list(sample.items())
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 124, in encode_based_on_extension1
    return handler(data)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 79, in <lambda>
    handlers[extension] = lambda data: imageencoder(data, extension_)
  File "/usr/local/lib/python3.6/dist-packages/webdataset/writer.py", line 49, in imageencoder
    image.save(result, format=format, **opts)
AttributeError: 'NpzFile' object has no attribute 'save'
```

I also tried loading those npz files as byte stream, with `open(file_path).read()` but that results in various encoding errors.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-1ff3c10e57c4>", line 2, in <module>
    for sample in islice(image_samples(), 0, 100):
  File "<ipython-input-23-fa0672ab6344>", line 8, in image_samples
    "image": image_fp.read(),
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 15: invalid continuation byte
```

**Comment by brtasavpatel** [comment]
opening the file in `binary` mode and reading the streams from it worked in this case.

closing this issue, but if anyone have a better way of reading `npz` files please do comment.
