### ISSUE TITLE
batched reading in Dataloader not working

### ISSUE THREAD

**Issue by brtasavpatel** [webdataset/webdataset#98]
I am trying to iterate over the dataset using pytorch's dataloader.

here's the code snippet which shows how I have created the dataset and how I am trying to read it.

```
import torch
import webdataset as wds
import pandas as pd
from itertools import islice
import imageio

# creating dataset
def image_samples(csv_path="metadata.csv"):
    df = pd.read_csv(csv_path)
    for row in df.itertuples():
        sample = {
            "__key__": row.image_id,
            "image.pyd": imageio.imread(row.image_path),
            "label.pyd": imageio.imread(row.label_path)
        }
        yield sample


with wds.ShardWriter("dataset-%06d.tar", maxcount=10) as sink:
    for sample in islice(image_samples(),0, 200):
        sink.write(sample)


# reading dataset
url = "dataset-{000000..000005}.tar"
batch_size = 4
num_workers = 4
dataset = (
    wds.WebDataset(url, shardshuffle=False).batched(batch_size)
    .decode("pil")
    .to_tuple("image.pyd", "label.pyd")
)

dataloader = torch.utils.data.DataLoader(dataset, num_workers=num_workers, batch_size=None)
for i_iter, batch in enumerate(dataloader):
    print(i_iter) # breaks here
    break
```

When I try to read the dataset I get this error :
```
Traceback (most recent call last):
  File "/Users/asav.patel/Library/Application Support/JetBrains/PyCharm2021.2/scratches/jupiter_scratch.py", line 39, in <module>
    for i_iter, batch in enumerate(dataloader):
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/iterators.py", line 230, in map
    if handler(exn):
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/utils.py", line 12, in reraise_exception
    raise exn
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/iterators.py", line 228, in map
    result = f(sample)
  File "/Users/asav.patel/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/autodecode.py", line 331, in __call__
    assert isinstance(sample, dict), (len(sample), sample)
AssertionError: (3, [['__key__', '__key__', '__key__', '__key__'], ['image.pyd', 'image.pyd', 'image.pyd', 'image.pyd'], ['label.pyd', 'label.pyd', 'label.pyd', 'label.pyd']])
```

What am I doing wrong here?

btw this works just fine :
```
# notice there's no `.batched(batch_size)` applied here.
dataset = (
    wds.WebDataset(url, shardshuffle=False)
    .decode("pil")
    .to_tuple("image.pyd", "label.pyd")
)

for sample in dataset:
    print(sample)
    break
    
wds_loader = wds.WebLoader(dataset, num_workers=num_workers, batch_size=batch_size)
for i_iter, batch in enumerate(wds_loader):
    print(i_iter)
    break

dataloader = torch.utils.data.DataLoader(dataset, num_workers=num_workers, batch_size=batch_size)
for i_iter, batch in enumerate(dataloader):
    print(i_iter)
    break 

```

**Comment by tmbdev** [comment]
You're batching before decoding. 

- Decoding needs to happen before batching, because the decoders expect individual samples and files for decoding.
- Furthermore, batching works on tensors, not on PIL images. 

This would work; it will write batches consisting of lists of PIL images to disk:

```
dataset = (
    wds.WebDataset(url, shardshuffle=False)
    .decode("pil")
    .listed(batch_size)
    .to_tuple("image.pyd", "label.pyd")
)
```

You probably want something more like:

```
dataset = (
    wds.WebDataset(url, shardshuffle=False)
    .decode("rgb8")
    .batched(batch_size)
    .to_tuple("image.pyd", "label.pyd")
)
```

But is there any reason to write whole batches to disk in the first place? Since WebDataset already does sequential reads, you don't gain I/O speed for writing unbatched images and batching upon read. Unless there is a functional reason for wanting to keep batches together (e.g. for reproducibility or because you constructed them according to some criteria), you're probably better off just writing individual samples.

**Comment by brtasavpatel** [comment]
@tmbdev Thanks for the response. Makes sense.
So what do you suggest? batch inside the `WebLoader` or `DataLoader`?

**Comment by tmbdev** [comment]
PyTorch pretty much requires you to do batching inside the Dataset for
sequential I/O; that's also good for efficiency.

If you use WebDataloader (a thin wrapper around DataLoader), you can
rebatch the data:

```
ds = WebDataset(...) ... .batched(64)
dl = WebDataloader(...).unbatched().batched(batch_size)
```
