### ISSUE TITLE
support for NPZ files?

### ISSUE THREAD

**Issue by brtasavpatel** [webdataset/webdataset#99]
Is there a way to save `npz` (numpy compressed) files when creating webdataset?
when I use `.pyd` extension and using `np.load()` to save npz file I get following error :
```
Traceback (most recent call last):
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 338, in write
    size = self.tarstream.write(obj)
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 252, in write
    obj = self.encoder(obj)
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 156, in encoder
    return encode_based_on_extension(sample, handlers)
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 131, in encode_based_on_extension
    k: encode_based_on_extension1(v, k, handlers) for k, v in list(sample.items())
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 131, in <dictcomp>
    k: encode_based_on_extension1(v, k, handlers) for k, v in list(sample.items())
  File "/home/asav/.pyenv/versions/jupiter_env/lib/python3.6/site-packages/webdataset/writer.py", line 126, in encode_based_on_extension1
    return handler(data)
TypeError: cannot serialize '_io.BufferedReader' object
```

**Comment by tmbdev** [comment]
`webdataset.writer.handlers` maps file extensions to functions; the function takes the object as input and needs to return `bytes`. Alternatively, you can also just convert to `bytes` before you invoke the writer; for objects of type `bytes`, the extensions and handlers are ignored (since the library assumes that you have already converted the data).

However, the specific reason you are getting that particular error is not because of anything related to the encoding of pyd or npz files, but because you put a BufferedReader into the sample, and BufferedReaders can't be encoded by anything.

TODO: provide context info in `encode_based_on_extension1` (including extension)
TODO: handle BufferedReader in `encode_based_on_extension1` with a special error message
TODO: add .npz support to encoding

**Comment by brtasavpatel** [comment]
Thanks for the info. Yeah I ended up saving byte streams.

I'll look into the code and see if I can contribute for `.npz` support.

**Comment by asavpatel92** [comment]
@tmbdev added a PR to add this support. please take a look at #102 :-)

**Comment by tmbdev** [comment]
Thanks!
